version: 2.1

jobs:
  run-tests:
    docker:
      - image: crystallang/crystal:1.6.0-alpine
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Install system dependencies"
          command: apk add --update --no-cache --force-overwrite nodejs npm make pcre2-dev
      - run:
          name: "Install server dependencies"
          command: shards install
      - run:
          name: "Install client dependencies"
          command: npm ci
      - run:
          name: "Lint server"
          command: make lint/server
      - run:
          name: "Lint client"
          command: make lint/server
      - run:
          name: "Run tests"
          command: |
            make run/tests
      - run:
          name: "Build project"
          command: make

workflows:
  test:
    jobs:
      - run-tests
