name: Security Review
on:
  push:
    branches: [master, protected]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  security-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
